version: "2"
services:
  jobmanager:
    image: flink
    expose:
      - "6123"
    ports:
      - "8077:8081"
    command: jobmanager
    volumes:
        - .:/script
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      
  taskmanager:
    image: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

